library(plotly)
set.seed(100)
d <- diamonds[sample(nrow(diamonds), 1000), ]
plot_ly(d, x  = carat, y = price, text = paste("Clarity: ", clarity), mode = "markers", color = carat, size = carat)
Sys.setenv("plotly_username"="TaiwoAyanleye")
plotly:::verify("username")
Sys.setenv("plotly_api_key"="hsqmzpn0i7")
plotly:::verify("apikey")
plotly:::verify("api_key")
plot_ly(d, x  = carat, y = price, text = paste("Clarity: ", clarity), mode = "markers", color = carat, size = carat)
